'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web

    Partial Public Class Edit

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''AdminNav1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AdminNav1 As Global.OSSCSC.Web.AdminNav

        '''<summary>
        '''lblID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUpdated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''drpCommissioner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCommissioner As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''chkIsPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsPublished As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''Labelforcontrol4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol4 As Global.OSSCSC.Web.LabelForControl

        '''<summary>
        '''drpNCNYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpNCNYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtNCNCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNCNCode1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpNCNCitation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpNCNCitation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtNCNCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNCNCode2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCaseNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaseNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Requiredfieldvalidator6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Requiredfieldvalidator6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RequiredFieldValidator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RangeValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''RequiredFieldValidator4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtReportedNumber1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportedNumber1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtReportedNumber2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportedNumber2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtReportedNumber3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportedNumber3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDecisionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDecisionDate As Global.OSSCSC.Web.HtmlDateControl

        '''<summary>
        '''CompareValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''RequiredFieldValidator5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtClaimant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClaimant As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Labelforcontrol3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol3 As Global.OSSCSC.Web.LabelForControl

        '''<summary>
        '''txtRespondent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRespondent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpMainCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpMainCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''drpMainSubCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpMainSubCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CompareValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompareValidator2 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''drpSecondaryCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSecondaryCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''drpSecondarySubCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSecondarySubCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''phLinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLinks As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''fileDecision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileDecision As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Button1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
