'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Web

    Partial Public Class AdminNav

        '''<summary>
        '''hrefSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrefSearch As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hrefCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrefCreate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hrefUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrefUsers As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hrefCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrefCategories As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hrefCommissioners control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrefCommissioners As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkSignOut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkSignOut As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
