'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DCA.TribunalsService.Ossc.Web

    Partial Public Class Search

        '''<summary>
        '''Header1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Header1 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.Header

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Labelforcontrol1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol1 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''drpCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Labelforcontrol2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol2 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''drpSubcategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSubcategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Labelforcontrol3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol3 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''txtDecisionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDecisionDate As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.HtmlDateControl

        '''<summary>
        '''Labelforcontrol8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol8 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''txtPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCase As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromDate As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.HtmlDateControl

        '''<summary>
        '''txtToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToDate As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.HtmlDateControl

        '''<summary>
        '''txtFromDateAdded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromDateAdded As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.HtmlDateControl

        '''<summary>
        '''txtToDateAdded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToDateAdded As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.HtmlDateControl

        '''<summary>
        '''txtClaimant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClaimant As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRespondent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRespondent As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Labelforcontrol7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol7 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''drpCommissioner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCommissioner As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Labelforcontrol4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol4 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''drpNCNYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpNCNYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''drpNCNCitation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpNCNCitation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Labelforcontrol9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol9 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''txtReported1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReported1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtReported2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReported2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtReported3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReported3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Labelforcontrol10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelforcontrol10 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.LabelForControl

        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DecisionGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DecisionGrid As Global.DCA.TribunalsService.Web.UI.Controls.GroupedGrid

        '''<summary>
        '''PagerControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PagerControl As Global.DCA.TribunalsService.Web.UI.Controls.Pager

        '''<summary>
        '''Footer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Footer1 As Global.OSSCSC.DCA.TribunalsService.Ossc.Web.Footer
    End Class
End Namespace
